version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: bookingService_user
      MYSQL_PASSWORD: bookingService_password
      MYSQL_DATABASE: bookingService
    volumes:
     - "/home/altug/Desktop/mySQLContainer/db:/var/lib/mysql"