CREATE TABLE IF NOT EXISTS USERDETAILS (
  ID MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRSTNAME    VARCHAR(100),
  LASTNAME    VARCHAR(100), 
  VERIFICATION VARCHAR(20),
  EMAILVERIFIED  BOOLEAN,
  EMAIL     VARCHAR(255),
  PASSWORD  VARCHAR(20),
  PHONE     VARCHAR(20)
);